version: 0.2

    
  pre_build:
    commands:
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
      - apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update
      - apt-get install -y trivy
  build:
    commands:
      - trivy repo https://github.com/Kunreddi/ar_web -o result.json
  post_build:
    commands:
      - echo Build completed on `date`
